name: Build and deploy
on:
  push:
    branches:
      - main
      - test

jobs:
  create-image-url:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_URL: ${{ steps.set_image_url.outputs.IMAGE_URL }}
    steps:
      - name: Get Github short sha
        uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - name: Preset Image URL
        id: set_image_url
        run: echo "IMAGE_URL=$(echo docker.io/${{ vars.DOCKERHUB_REPOSITORY_NAME }}:pokedex-vue2-$(echo ${{ github.ref_name }})-$(echo ${{ steps.short-sha.outputs.sha }}))" >> $GITHUB_OUTPUT

  build:
    needs: create-image-url
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ needs.create-image-url.outputs.IMAGE_URL }}

  deploy:
    needs: [create-image-url, build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Image to CapRrover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app: ${{ secrets.CAPROVER_APP_NAME }}
          token: ${{ secrets.CAPROVER_APP_TOKEN }}
          image: ${{ needs.create-image-url.outputs.IMAGE_URL }}